var annotated_dup =
[
    [ "GUIConstants", "namespaceGUIConstants.html", [
      [ "Resolution", "structGUIConstants_1_1Resolution.html", "structGUIConstants_1_1Resolution" ]
    ] ],
    [ "Button", "structButton.html", "structButton" ],
    [ "ButtonManager", "classButtonManager.html", "classButtonManager" ],
    [ "ButtonStyle", "structButtonStyle.html", "structButtonStyle" ],
    [ "Calendar", "classCalendar.html", "classCalendar" ],
    [ "DatabaseConnection", "classDatabaseConnection.html", "classDatabaseConnection" ],
    [ "DatabaseException", "classDatabaseException.html", null ],
    [ "DataGenerator", "classDataGenerator.html", "classDataGenerator" ],
    [ "Dropdown", "classDropdown.html", "classDropdown" ],
    [ "DropdownStyle", "structDropdownStyle.html", "structDropdownStyle" ],
    [ "Finances", "classFinances.html", "classFinances" ],
    [ "FixtureRepository", "classFixtureRepository.html", "classFixtureRepository" ],
    [ "Game", "classGame.html", "classGame" ],
    [ "GameController", "classGameController.html", "classGameController" ],
    [ "GameData", "classGameData.html", "classGameData" ],
    [ "GameDate", "classGameDate.html", "classGameDate" ],
    [ "GameDateValue", "structGameDateValue.html", "structGameDateValue" ],
    [ "GameStateRepository", "classGameStateRepository.html", "classGameStateRepository" ],
    [ "GUIScene", "classGUIScene.html", "classGUIScene" ],
    [ "GUIView", "classGUIView.html", "classGUIView" ],
    [ "LanguageManager", "classLanguageManager.html", "classLanguageManager" ],
    [ "League", "classLeague.html", "classLeague" ],
    [ "LeagueRepository", "classLeagueRepository.html", "classLeagueRepository" ],
    [ "Lineup", "classLineup.html", "classLineup" ],
    [ "Logger", "classLogger.html", "classLogger" ],
    [ "MainGameScene", "classMainGameScene.html", "classMainGameScene" ],
    [ "MainMenuScene", "classMainMenuScene.html", "classMainMenuScene" ],
    [ "Match", "classMatch.html", "classMatch" ],
    [ "Matchup", "structMatchup.html", "structMatchup" ],
    [ "Player", "classPlayer.html", "classPlayer" ],
    [ "PlayerRepository", "classPlayerRepository.html", "classPlayerRepository" ],
    [ "QueryMapEntry", "structQueryMapEntry.html", "structQueryMapEntry" ],
    [ "RoleFocus", "structRoleFocus.html", "structRoleFocus" ],
    [ "RoleWeights", "structRoleWeights.html", "structRoleWeights" ],
    [ "RosterScene", "classRosterScene.html", "classRosterScene" ],
    [ "Settings", "structSettings.html", "structSettings" ],
    [ "SettingsManager", "classSettingsManager.html", "classSettingsManager" ],
    [ "SettingsScene", "classSettingsScene.html", "classSettingsScene" ],
    [ "SQLLoader", "classSQLLoader.html", "classSQLLoader" ],
    [ "StatsConfig", "structStatsConfig.html", "structStatsConfig" ],
    [ "Strategy", "classStrategy.html", "classStrategy" ],
    [ "StrategyScene", "classStrategyScene.html", "classStrategyScene" ],
    [ "StrategySliders", "structStrategySliders.html", "structStrategySliders" ],
    [ "Team", "classTeam.html", "classTeam" ],
    [ "TeamRepository", "classTeamRepository.html", "classTeamRepository" ],
    [ "TeamSelectionScene", "classTeamSelectionScene.html", "classTeamSelectionScene" ]
];