var annotated_dup =
[
    [ "Audio", "namespaceAudio.html", [
      [ "AudioDevice", "classAudio_1_1AudioDevice.html", "classAudio_1_1AudioDevice" ],
      [ "BusLevels", "structAudio_1_1BusLevels.html", "structAudio_1_1BusLevels" ],
      [ "CrowdBed", "classAudio_1_1CrowdBed.html", "classAudio_1_1CrowdBed" ],
      [ "Darken", "classAudio_1_1Darken.html", "classAudio_1_1Darken" ],
      [ "Drift", "classAudio_1_1Drift.html", "classAudio_1_1Drift" ],
      [ "Mixer", "classAudio_1_1Mixer.html", "classAudio_1_1Mixer" ],
      [ "Noise", "classAudio_1_1Noise.html", "classAudio_1_1Noise" ],
      [ "OnePole", "classAudio_1_1OnePole.html", "classAudio_1_1OnePole" ],
      [ "SoundCommand", "structAudio_1_1SoundCommand.html", "structAudio_1_1SoundCommand" ],
      [ "Svf", "classAudio_1_1Svf.html", "classAudio_1_1Svf" ],
      [ "Voice", "classAudio_1_1Voice.html", "classAudio_1_1Voice" ]
    ] ],
    [ "BuyerNegotiation", "namespaceBuyerNegotiation.html", [
      [ "BuyerContext", "structBuyerNegotiation_1_1BuyerContext.html", "structBuyerNegotiation_1_1BuyerContext" ],
      [ "BuyerReply", "structBuyerNegotiation_1_1BuyerReply.html", "structBuyerNegotiation_1_1BuyerReply" ],
      [ "RejectionEffect", "structBuyerNegotiation_1_1RejectionEffect.html", "structBuyerNegotiation_1_1RejectionEffect" ],
      [ "StanceFacts", "structBuyerNegotiation_1_1StanceFacts.html", "structBuyerNegotiation_1_1StanceFacts" ]
    ] ],
    [ "Competitions", "namespaceCompetitions.html", [
      [ "CupDraw", "structCompetitions_1_1CupDraw.html", "structCompetitions_1_1CupDraw" ],
      [ "CupRound", "structCompetitions_1_1CupRound.html", "structCompetitions_1_1CupRound" ],
      [ "CupStatus", "structCompetitions_1_1CupStatus.html", "structCompetitions_1_1CupStatus" ],
      [ "KnockoutResolution", "structCompetitions_1_1KnockoutResolution.html", "structCompetitions_1_1KnockoutResolution" ],
      [ "LeagueMovement", "structCompetitions_1_1LeagueMovement.html", "structCompetitions_1_1LeagueMovement" ],
      [ "ShootoutResult", "structCompetitions_1_1ShootoutResult.html", "structCompetitions_1_1ShootoutResult" ]
    ] ],
    [ "CompetitionView", "namespaceCompetitionView.html", [
      [ "FixtureRow", "structCompetitionView_1_1FixtureRow.html", "structCompetitionView_1_1FixtureRow" ],
      [ "StandingRow", "structCompetitionView_1_1StandingRow.html", "structCompetitionView_1_1StandingRow" ],
      [ "Zones", "structCompetitionView_1_1Zones.html", "structCompetitionView_1_1Zones" ]
    ] ],
    [ "Continental", "namespaceContinental.html", [
      [ "CompetitionRules", "structContinental_1_1CompetitionRules.html", "structContinental_1_1CompetitionRules" ],
      [ "DrawTeam", "structContinental_1_1DrawTeam.html", "structContinental_1_1DrawTeam" ],
      [ "LeagueFixture", "structContinental_1_1LeagueFixture.html", "structContinental_1_1LeagueFixture" ],
      [ "Prizes", "structContinental_1_1Prizes.html", "structContinental_1_1Prizes" ]
    ] ],
    [ "CrashReport", "namespaceCrashReport.html", [
      [ "Pending", "structCrashReport_1_1Pending.html", "structCrashReport_1_1Pending" ]
    ] ],
    [ "Credits", "namespaceCredits.html", [
      [ "Component", "structCredits_1_1Component.html", "structCredits_1_1Component" ]
    ] ],
    [ "Formation", "namespaceFormation.html", [
      [ "Preset", "structFormation_1_1Preset.html", "structFormation_1_1Preset" ],
      [ "Slot", "structFormation_1_1Slot.html", "structFormation_1_1Slot" ]
    ] ],
    [ "Glossary", "namespaceGlossary.html", [
      [ "Term", "structGlossary_1_1Term.html", "structGlossary_1_1Term" ]
    ] ],
    [ "GUIConstants", "namespaceGUIConstants.html", [
      [ "Resolution", "structGUIConstants_1_1Resolution.html", "structGUIConstants_1_1Resolution" ]
    ] ],
    [ "InboxDilemmaCard", "namespaceInboxDilemmaCard.html", [
      [ "EffectLine", "structInboxDilemmaCard_1_1EffectLine.html", "structInboxDilemmaCard_1_1EffectLine" ]
    ] ],
    [ "Input", "namespaceInput.html", [
      [ "Action", "structInput_1_1Action.html", "structInput_1_1Action" ],
      [ "ActionDef", "structInput_1_1ActionDef.html", "structInput_1_1ActionDef" ],
      [ "ActionRegistry", "classInput_1_1ActionRegistry.html", "classInput_1_1ActionRegistry" ],
      [ "RebindResult", "structInput_1_1RebindResult.html", "structInput_1_1RebindResult" ]
    ] ],
    [ "International", "namespaceInternational.html", [
      [ "Fixture", "structInternational_1_1Fixture.html", "structInternational_1_1Fixture" ],
      [ "Group", "structInternational_1_1Group.html", "structInternational_1_1Group" ],
      [ "GroupRow", "structInternational_1_1GroupRow.html", "structInternational_1_1GroupRow" ],
      [ "Record", "structInternational_1_1Record.html", "structInternational_1_1Record" ]
    ] ],
    [ "Lab", "namespaceLab.html", [
      [ "Band", "structLab_1_1Band.html", "structLab_1_1Band" ],
      [ "Estimate", "structLab_1_1Estimate.html", "structLab_1_1Estimate" ],
      [ "LabReport", "structLab_1_1LabReport.html", "structLab_1_1LabReport" ],
      [ "MatchJob", "structLab_1_1MatchJob.html", "structLab_1_1MatchJob" ],
      [ "MatchSample", "structLab_1_1MatchSample.html", "structLab_1_1MatchSample" ],
      [ "ReportRow", "structLab_1_1ReportRow.html", "structLab_1_1ReportRow" ],
      [ "SeasonOptions", "structLab_1_1SeasonOptions.html", "structLab_1_1SeasonOptions" ],
      [ "SeasonVitals", "structLab_1_1SeasonVitals.html", "structLab_1_1SeasonVitals" ],
      [ "SimulationError", "classLab_1_1SimulationError.html", "classLab_1_1SimulationError" ],
      [ "Summary", "structLab_1_1Summary.html", "structLab_1_1Summary" ],
      [ "TacticPreset", "structLab_1_1TacticPreset.html", "structLab_1_1TacticPreset" ],
      [ "TargetSpec", "structLab_1_1TargetSpec.html", "structLab_1_1TargetSpec" ],
      [ "TeamSetup", "structLab_1_1TeamSetup.html", "structLab_1_1TeamSetup" ],
      [ "TextTable", "structLab_1_1TextTable.html", "structLab_1_1TextTable" ],
      [ "TierVitals", "structLab_1_1TierVitals.html", "structLab_1_1TierVitals" ]
    ] ],
    [ "LoanNegotiation", "namespaceLoanNegotiation.html", [
      [ "BorrowerContext", "structLoanNegotiation_1_1BorrowerContext.html", "structLoanNegotiation_1_1BorrowerContext" ],
      [ "BorrowerReply", "structLoanNegotiation_1_1BorrowerReply.html", "structLoanNegotiation_1_1BorrowerReply" ]
    ] ],
    [ "MatchChanges", "namespaceMatchChanges.html", [
      [ "PlannedSubstitution", "structMatchChanges_1_1PlannedSubstitution.html", "structMatchChanges_1_1PlannedSubstitution" ],
      [ "ShoutInfo", "structMatchChanges_1_1ShoutInfo.html", "structMatchChanges_1_1ShoutInfo" ],
      [ "SliderInfo", "structMatchChanges_1_1SliderInfo.html", "structMatchChanges_1_1SliderInfo" ],
      [ "SubstitutionOutcome", "structMatchChanges_1_1SubstitutionOutcome.html", "structMatchChanges_1_1SubstitutionOutcome" ],
      [ "SubstitutionPlan", "classMatchChanges_1_1SubstitutionPlan.html", "classMatchChanges_1_1SubstitutionPlan" ],
      [ "Suggestion", "structMatchChanges_1_1Suggestion.html", "structMatchChanges_1_1Suggestion" ],
      [ "TacticPreset", "structMatchChanges_1_1TacticPreset.html", "structMatchChanges_1_1TacticPreset" ]
    ] ],
    [ "MatchRules", "namespaceMatchRules.html", [
      [ "FoulContext", "structMatchRules_1_1FoulContext.html", "structMatchRules_1_1FoulContext" ],
      [ "Knockout", "structMatchRules_1_1Knockout.html", "structMatchRules_1_1Knockout" ],
      [ "StoppageLog", "structMatchRules_1_1StoppageLog.html", "structMatchRules_1_1StoppageLog" ],
      [ "TackleContext", "structMatchRules_1_1TackleContext.html", "structMatchRules_1_1TackleContext" ]
    ] ],
    [ "Migrations", "namespaceMigrations.html", [
      [ "ColumnSpec", "structMigrations_1_1ColumnSpec.html", "structMigrations_1_1ColumnSpec" ],
      [ "FutureVersionError", "classMigrations_1_1FutureVersionError.html", "classMigrations_1_1FutureVersionError" ],
      [ "Migration", "structMigrations_1_1Migration.html", "structMigrations_1_1Migration" ],
      [ "MigrationContext", "structMigrations_1_1MigrationContext.html", "structMigrations_1_1MigrationContext" ],
      [ "MigrationReport", "structMigrations_1_1MigrationReport.html", "structMigrations_1_1MigrationReport" ]
    ] ],
    [ "NumberFormat", "namespaceNumberFormat.html", [
      [ "Locale", "structNumberFormat_1_1Locale.html", "structNumberFormat_1_1Locale" ],
      [ "MoneyParse", "structNumberFormat_1_1MoneyParse.html", "structNumberFormat_1_1MoneyParse" ]
    ] ],
    [ "PlayerAgent", "namespacePlayerAgent.html", [
      [ "Demands", "structPlayerAgent_1_1Demands.html", "structPlayerAgent_1_1Demands" ],
      [ "Reply", "structPlayerAgent_1_1Reply.html", "structPlayerAgent_1_1Reply" ]
    ] ],
    [ "PlayerRig", "namespacePlayerRig.html", [
      [ "ActionInput", "structPlayerRig_1_1ActionInput.html", "structPlayerRig_1_1ActionInput" ],
      [ "FootState", "structPlayerRig_1_1FootState.html", "structPlayerRig_1_1FootState" ],
      [ "GaitBands", "structPlayerRig_1_1GaitBands.html", "structPlayerRig_1_1GaitBands" ],
      [ "KickTiming", "structPlayerRig_1_1KickTiming.html", "structPlayerRig_1_1KickTiming" ],
      [ "StrideInput", "structPlayerRig_1_1StrideInput.html", "structPlayerRig_1_1StrideInput" ],
      [ "Swing", "structPlayerRig_1_1Swing.html", "structPlayerRig_1_1Swing" ],
      [ "TwoBone", "structPlayerRig_1_1TwoBone.html", "structPlayerRig_1_1TwoBone" ]
    ] ],
    [ "PlayerView", "namespacePlayerView.html", [
      [ "AttributeGroup", "structPlayerView_1_1AttributeGroup.html", "structPlayerView_1_1AttributeGroup" ],
      [ "PlayerRow", "structPlayerView_1_1PlayerRow.html", "structPlayerView_1_1PlayerRow" ],
      [ "RoleFit", "structPlayerView_1_1RoleFit.html", "structPlayerView_1_1RoleFit" ]
    ] ],
    [ "RenderMath", "namespaceRenderMath.html", [
      [ "Mat4", "structRenderMath_1_1Mat4.html", "structRenderMath_1_1Mat4" ],
      [ "Projection", "structRenderMath_1_1Projection.html", "structRenderMath_1_1Projection" ],
      [ "ScreenPoint", "structRenderMath_1_1ScreenPoint.html", "structRenderMath_1_1ScreenPoint" ],
      [ "ScreenRect", "structRenderMath_1_1ScreenRect.html", "structRenderMath_1_1ScreenRect" ],
      [ "ShirtNumbers", "classRenderMath_1_1ShirtNumbers.html", "classRenderMath_1_1ShirtNumbers" ],
      [ "Vec3", "structRenderMath_1_1Vec3.html", "structRenderMath_1_1Vec3" ],
      [ "Vec4", "structRenderMath_1_1Vec4.html", "structRenderMath_1_1Vec4" ]
    ] ],
    [ "SeasonCalendar", "namespaceSeasonCalendar.html", [
      [ "InternationalWindow", "structSeasonCalendar_1_1InternationalWindow.html", "structSeasonCalendar_1_1InternationalWindow" ]
    ] ],
    [ "SeasonReviewModel", "namespaceSeasonReviewModel.html", [
      [ "EventNames", "structSeasonReviewModel_1_1EventNames.html", "structSeasonReviewModel_1_1EventNames" ]
    ] ],
    [ "SquadNumbers", "namespaceSquadNumbers.html", [
      [ "Entry", "structSquadNumbers_1_1Entry.html", "structSquadNumbers_1_1Entry" ]
    ] ],
    [ "Stadium3D", "namespaceStadium3D.html", [
      [ "AdBoard", "structStadium3D_1_1AdBoard.html", "structStadium3D_1_1AdBoard" ],
      [ "Box", "structStadium3D_1_1Box.html", "structStadium3D_1_1Box" ],
      [ "CrowdClump", "structStadium3D_1_1CrowdClump.html", "structStadium3D_1_1CrowdClump" ],
      [ "CrowdDot", "structStadium3D_1_1CrowdDot.html", "structStadium3D_1_1CrowdDot" ],
      [ "CrowdFlag", "structStadium3D_1_1CrowdFlag.html", "structStadium3D_1_1CrowdFlag" ],
      [ "Face", "structStadium3D_1_1Face.html", "structStadium3D_1_1Face" ],
      [ "Geometry", "structStadium3D_1_1Geometry.html", "structStadium3D_1_1Geometry" ],
      [ "Goal", "structStadium3D_1_1Goal.html", "structStadium3D_1_1Goal" ],
      [ "GroundPolygon", "structStadium3D_1_1GroundPolygon.html", "structStadium3D_1_1GroundPolygon" ],
      [ "NetPanel", "structStadium3D_1_1NetPanel.html", "structStadium3D_1_1NetPanel" ],
      [ "PitchGrid", "structStadium3D_1_1PitchGrid.html", "structStadium3D_1_1PitchGrid" ],
      [ "Section", "structStadium3D_1_1Section.html", "structStadium3D_1_1Section" ],
      [ "SponsorStyle", "structStadium3D_1_1SponsorStyle.html", "structStadium3D_1_1SponsorStyle" ]
    ] ],
    [ "Standings", "namespaceStandings.html", [
      [ "ClinchReport", "structStandings_1_1ClinchReport.html", "structStandings_1_1ClinchReport" ],
      [ "RaceFixture", "structStandings_1_1RaceFixture.html", "structStandings_1_1RaceFixture" ],
      [ "RaceInput", "structStandings_1_1RaceInput.html", "structStandings_1_1RaceInput" ],
      [ "RaceNeed", "structStandings_1_1RaceNeed.html", "structStandings_1_1RaceNeed" ],
      [ "RacePlaces", "structStandings_1_1RacePlaces.html", "structStandings_1_1RacePlaces" ]
    ] ],
    [ "Theme", "namespaceTheme.html", [
      [ "Appearance", "structTheme_1_1Appearance.html", "structTheme_1_1Appearance" ],
      [ "Palette", "structTheme_1_1Palette.html", "structTheme_1_1Palette" ],
      [ "ScopedText", "classTheme_1_1ScopedText.html", "classTheme_1_1ScopedText" ],
      [ "Swatch", "structTheme_1_1Swatch.html", "structTheme_1_1Swatch" ]
    ] ],
    [ "TransferNegotiation", "namespaceTransferNegotiation.html", [
      [ "ClubResponse", "structTransferNegotiation_1_1ClubResponse.html", "structTransferNegotiation_1_1ClubResponse" ],
      [ "ContractDemand", "structTransferNegotiation_1_1ContractDemand.html", "structTransferNegotiation_1_1ContractDemand" ],
      [ "ContractOffer", "structTransferNegotiation_1_1ContractOffer.html", "structTransferNegotiation_1_1ContractOffer" ],
      [ "ContractResponse", "structTransferNegotiation_1_1ContractResponse.html", "structTransferNegotiation_1_1ContractResponse" ],
      [ "LoanContext", "structTransferNegotiation_1_1LoanContext.html", "structTransferNegotiation_1_1LoanContext" ],
      [ "LoanTerms", "structTransferNegotiation_1_1LoanTerms.html", "structTransferNegotiation_1_1LoanTerms" ],
      [ "OfferTerms", "structTransferNegotiation_1_1OfferTerms.html", "structTransferNegotiation_1_1OfferTerms" ],
      [ "PlayerContext", "structTransferNegotiation_1_1PlayerContext.html", "structTransferNegotiation_1_1PlayerContext" ],
      [ "PositionNeed", "structTransferNegotiation_1_1PositionNeed.html", "structTransferNegotiation_1_1PositionNeed" ],
      [ "SaleContext", "structTransferNegotiation_1_1SaleContext.html", "structTransferNegotiation_1_1SaleContext" ],
      [ "SquadFit", "structTransferNegotiation_1_1SquadFit.html", "structTransferNegotiation_1_1SquadFit" ],
      [ "SquadNeeds", "structTransferNegotiation_1_1SquadNeeds.html", "structTransferNegotiation_1_1SquadNeeds" ],
      [ "Valuation", "structTransferNegotiation_1_1Valuation.html", "structTransferNegotiation_1_1Valuation" ],
      [ "WindowInfo", "structTransferNegotiation_1_1WindowInfo.html", "structTransferNegotiation_1_1WindowInfo" ]
    ] ],
    [ "TransferWindows", "namespaceTransferWindows.html", [
      [ "CountryRules", "structTransferWindows_1_1CountryRules.html", "structTransferWindows_1_1CountryRules" ],
      [ "MonthDay", "structTransferWindows_1_1MonthDay.html", "structTransferWindows_1_1MonthDay" ],
      [ "Period", "structTransferWindows_1_1Period.html", "structTransferWindows_1_1Period" ]
    ] ],
    [ "UI", "namespaceUI.html", [
      [ "BarDatum", "structUI_1_1BarDatum.html", "structUI_1_1BarDatum" ],
      [ "Column", "structUI_1_1Column.html", "structUI_1_1Column" ],
      [ "MoneyChip", "structUI_1_1MoneyChip.html", "structUI_1_1MoneyChip" ],
      [ "MoneyInputOptions", "structUI_1_1MoneyInputOptions.html", "structUI_1_1MoneyInputOptions" ],
      [ "MoneyPreview", "structUI_1_1MoneyPreview.html", "structUI_1_1MoneyPreview" ],
      [ "TileRow", "classUI_1_1TileRow.html", "classUI_1_1TileRow" ]
    ] ],
    [ "AboutScene", "classAboutScene.html", "classAboutScene" ],
    [ "AcademyClub", "structAcademyClub.html", "structAcademyClub" ],
    [ "AcademyRatings", "structAcademyRatings.html", "structAcademyRatings" ],
    [ "AdviceInputs", "structAdviceInputs.html", "structAdviceInputs" ],
    [ "AgendaEvent", "structAgendaEvent.html", "structAgendaEvent" ],
    [ "AiManager", "structAiManager.html", "structAiManager" ],
    [ "AllTimeRow", "structAllTimeRow.html", "structAllTimeRow" ],
    [ "AnalysisInput", "structAnalysisInput.html", "structAnalysisInput" ],
    [ "AnalysisLine", "structAnalysisLine.html", "structAnalysisLine" ],
    [ "AnalysisSuggestion", "structAnalysisSuggestion.html", "structAnalysisSuggestion" ],
    [ "AutosavePolicy", "structAutosavePolicy.html", "structAutosavePolicy" ],
    [ "AwardCandidate", "structAwardCandidate.html", "structAwardCandidate" ],
    [ "AwardClubTally", "structAwardClubTally.html", "structAwardClubTally" ],
    [ "AwardPlayerTally", "structAwardPlayerTally.html", "structAwardPlayerTally" ],
    [ "AwardRecord", "structAwardRecord.html", "structAwardRecord" ],
    [ "AwardsScene", "classAwardsScene.html", "classAwardsScene" ],
    [ "AwardSystem", "classAwardSystem.html", "classAwardSystem" ],
    [ "BoardState", "structBoardState.html", "structBoardState" ],
    [ "Button", "structButton.html", "structButton" ],
    [ "ButtonManager", "classButtonManager.html", "classButtonManager" ],
    [ "ButtonStyle", "structButtonStyle.html", "structButtonStyle" ],
    [ "Calendar", "classCalendar.html", "classCalendar" ],
    [ "CalendarScene", "classCalendarScene.html", "classCalendarScene" ],
    [ "CallUpScene", "classCallUpScene.html", "classCallUpScene" ],
    [ "CampQuote", "structCampQuote.html", "structCampQuote" ],
    [ "CandidateProfile", "structCandidateProfile.html", "structCandidateProfile" ],
    [ "CareerDayEvents", "structCareerDayEvents.html", "structCareerDayEvents" ],
    [ "CareerGuidance", "classCareerGuidance.html", "classCareerGuidance" ],
    [ "CareerTotals", "structCareerTotals.html", "structCareerTotals" ],
    [ "ClubColours", "structClubColours.html", "structClubColours" ],
    [ "ClubIdentity", "structClubIdentity.html", "structClubIdentity" ],
    [ "ClubPlayerTotal", "structClubPlayerTotal.html", "structClubPlayerTotal" ],
    [ "ClubProfile", "structClubProfile.html", "structClubProfile" ],
    [ "ClubScene", "classClubScene.html", "classClubScene" ],
    [ "ClubVision", "structClubVision.html", "structClubVision" ],
    [ "CompetitionManager", "classCompetitionManager.html", "classCompetitionManager" ],
    [ "CompetitionRepository", "classCompetitionRepository.html", "classCompetitionRepository" ],
    [ "ContinentalCompetitions", "classContinentalCompetitions.html", "classContinentalCompetitions" ],
    [ "ContractExpiry", "structContractExpiry.html", "structContractExpiry" ],
    [ "ContractTalksDialog", "classContractTalksDialog.html", "classContractTalksDialog" ],
    [ "CounterTactic", "structCounterTactic.html", "structCounterTactic" ],
    [ "DatabaseConnection", "classDatabaseConnection.html", "classDatabaseConnection" ],
    [ "DatabaseException", "classDatabaseException.html", null ],
    [ "DataGenerator", "classDataGenerator.html", "classDataGenerator" ],
    [ "DataHubInput", "structDataHubInput.html", "structDataHubInput" ],
    [ "DataHubScene", "classDataHubScene.html", "classDataHubScene" ],
    [ "DelegationPolicy", "classDelegationPolicy.html", "classDelegationPolicy" ],
    [ "DelegationScene", "classDelegationScene.html", "classDelegationScene" ],
    [ "DepthEntry", "structDepthEntry.html", "structDepthEntry" ],
    [ "DetailPlayer", "structDetailPlayer.html", "structDetailPlayer" ],
    [ "DetailSubstitution", "structDetailSubstitution.html", "structDetailSubstitution" ],
    [ "Dilemma", "structDilemma.html", "structDilemma" ],
    [ "DilemmaEffects", "structDilemmaEffects.html", "structDilemmaEffects" ],
    [ "DisciplinaryRecord", "structDisciplinaryRecord.html", "structDisciplinaryRecord" ],
    [ "Discipline", "classDiscipline.html", "classDiscipline" ],
    [ "DisciplineRules", "structDisciplineRules.html", "structDisciplineRules" ],
    [ "DrawCeremony", "structDrawCeremony.html", "structDrawCeremony" ],
    [ "DrawCeremonyDialog", "classDrawCeremonyDialog.html", "classDrawCeremonyDialog" ],
    [ "DrawReveal", "structDrawReveal.html", "structDrawReveal" ],
    [ "DressingRoom", "structDressingRoom.html", "structDressingRoom" ],
    [ "Dropdown", "classDropdown.html", "classDropdown" ],
    [ "DropdownStyle", "structDropdownStyle.html", "structDropdownStyle" ],
    [ "EffectFactor", "structEffectFactor.html", "structEffectFactor" ],
    [ "FacilityProject", "structFacilityProject.html", "structFacilityProject" ],
    [ "FacilityProjects", "classFacilityProjects.html", "classFacilityProjects" ],
    [ "FinanceRepository", "classFinanceRepository.html", "classFinanceRepository" ],
    [ "Finances", "classFinances.html", "classFinances" ],
    [ "FinanceSummary", "structFinanceSummary.html", "structFinanceSummary" ],
    [ "FinanceTransaction", "structFinanceTransaction.html", "structFinanceTransaction" ],
    [ "FixtureRepository", "classFixtureRepository.html", "classFixtureRepository" ],
    [ "FixturesScene", "classFixturesScene.html", "classFixturesScene" ],
    [ "FollowedPlayer", "structFollowedPlayer.html", "structFollowedPlayer" ],
    [ "FriendlySlot", "structFriendlySlot.html", "structFriendlySlot" ],
    [ "FriendlySuggestion", "structFriendlySuggestion.html", "structFriendlySuggestion" ],
    [ "Game", "classGame.html", "classGame" ],
    [ "GameController", "classGameController.html", "classGameController" ],
    [ "GameData", "classGameData.html", "classGameData" ],
    [ "GameDate", "classGameDate.html", "classGameDate" ],
    [ "GameDateValue", "structGameDateValue.html", "structGameDateValue" ],
    [ "GameStateRepository", "classGameStateRepository.html", "classGameStateRepository" ],
    [ "GoalCandidate", "structGoalCandidate.html", "structGoalCandidate" ],
    [ "GroupDepth", "structGroupDepth.html", "structGroupDepth" ],
    [ "GUIScene", "classGUIScene.html", "classGUIScene" ],
    [ "GUIView", "classGUIView.html", "classGUIView" ],
    [ "HeadOfYouth", "structHeadOfYouth.html", "structHeadOfYouth" ],
    [ "HelpScene", "classHelpScene.html", "classHelpScene" ],
    [ "HolidayDay", "structHolidayDay.html", "structHolidayDay" ],
    [ "HolidayDialog", "classHolidayDialog.html", "classHolidayDialog" ],
    [ "HolidayInjury", "structHolidayInjury.html", "structHolidayInjury" ],
    [ "HolidayMove", "structHolidayMove.html", "structHolidayMove" ],
    [ "HolidayOffer", "structHolidayOffer.html", "structHolidayOffer" ],
    [ "HolidayPlan", "structHolidayPlan.html", "structHolidayPlan" ],
    [ "HolidayPreferences", "structHolidayPreferences.html", "structHolidayPreferences" ],
    [ "HolidayResult", "structHolidayResult.html", "structHolidayResult" ],
    [ "HolidaySummary", "structHolidaySummary.html", "structHolidaySummary" ],
    [ "IMatchRenderer", "classIMatchRenderer.html", "classIMatchRenderer" ],
    [ "Inbox", "classInbox.html", "classInbox" ],
    [ "InboxMessage", "structInboxMessage.html", "structInboxMessage" ],
    [ "InboxRepository", "classInboxRepository.html", "classInboxRepository" ],
    [ "InboxScene", "classInboxScene.html", "classInboxScene" ],
    [ "InboxView", "structInboxView.html", "structInboxView" ],
    [ "IncomingOffer", "structIncomingOffer.html", "structIncomingOffer" ],
    [ "Injury", "structInjury.html", "structInjury" ],
    [ "InjuryRiskAssessment", "structInjuryRiskAssessment.html", "structInjuryRiskAssessment" ],
    [ "InjuryRiskInputs", "structInjuryRiskInputs.html", "structInjuryRiskInputs" ],
    [ "InsightInput", "structInsightInput.html", "structInsightInput" ],
    [ "IntakeClass", "structIntakeClass.html", "structIntakeClass" ],
    [ "IntakeInputs", "structIntakeInputs.html", "structIntakeInputs" ],
    [ "IntakePreview", "structIntakePreview.html", "structIntakePreview" ],
    [ "InteractionState", "structInteractionState.html", "structInteractionState" ],
    [ "InteractionSystem", "classInteractionSystem.html", "classInteractionSystem" ],
    [ "InternationalScene", "classInternationalScene.html", "classInternationalScene" ],
    [ "InterviewResult", "structInterviewResult.html", "structInterviewResult" ],
    [ "JobApplication", "structJobApplication.html", "structJobApplication" ],
    [ "JobOffer", "structJobOffer.html", "structJobOffer" ],
    [ "KeyMoment", "structKeyMoment.html", "structKeyMoment" ],
    [ "KeyOpponent", "structKeyOpponent.html", "structKeyOpponent" ],
    [ "KitColors", "structKitColors.html", "structKitColors" ],
    [ "LanguageManager", "classLanguageManager.html", "classLanguageManager" ],
    [ "LeaderInfo", "structLeaderInfo.html", "structLeaderInfo" ],
    [ "League", "classLeague.html", "classLeague" ],
    [ "LeagueEconomy", "structLeagueEconomy.html", "structLeagueEconomy" ],
    [ "LeagueMatchStyle", "structLeagueMatchStyle.html", "structLeagueMatchStyle" ],
    [ "LeagueProfile", "structLeagueProfile.html", "structLeagueProfile" ],
    [ "LeagueRepository", "classLeagueRepository.html", "classLeagueRepository" ],
    [ "LeagueShape", "structLeagueShape.html", "structLeagueShape" ],
    [ "LegendEntry", "structLegendEntry.html", "structLegendEntry" ],
    [ "Lineup", "classLineup.html", "classLineup" ],
    [ "LineupScene", "classLineupScene.html", "classLineupScene" ],
    [ "LoadChartDay", "structLoadChartDay.html", "structLoadChartDay" ],
    [ "LoanDeal", "structLoanDeal.html", "structLoanDeal" ],
    [ "Logger", "classLogger.html", "classLogger" ],
    [ "MainGameScene", "classMainGameScene.html", "classMainGameScene" ],
    [ "MainMenuScene", "classMainMenuScene.html", "classMainMenuScene" ],
    [ "ManagedMatchSnapshot", "structManagedMatchSnapshot.html", "structManagedMatchSnapshot" ],
    [ "ManagementScene", "classManagementScene.html", "classManagementScene" ],
    [ "ManagerAward", "structManagerAward.html", "structManagerAward" ],
    [ "ManagerCareer", "classManagerCareer.html", "classManagerCareer" ],
    [ "ManagerContract", "structManagerContract.html", "structManagerContract" ],
    [ "ManagerProfile", "structManagerProfile.html", "structManagerProfile" ],
    [ "ManagerScene", "classManagerScene.html", "classManagerScene" ],
    [ "ManagerSeasonLine", "structManagerSeasonLine.html", "structManagerSeasonLine" ],
    [ "ManagerSetup", "structManagerSetup.html", "structManagerSetup" ],
    [ "ManagerSetupPanel", "classManagerSetupPanel.html", "classManagerSetupPanel" ],
    [ "ManagerStint", "structManagerStint.html", "structManagerStint" ],
    [ "Match", "classMatch.html", "classMatch" ],
    [ "MatchAnalysis", "structMatchAnalysis.html", "structMatchAnalysis" ],
    [ "MatchAnalysisPanel", "classMatchAnalysisPanel.html", "classMatchAnalysisPanel" ],
    [ "MatchAudio", "classMatchAudio.html", "classMatchAudio" ],
    [ "MatchAudioFrame", "structMatchAudioFrame.html", "structMatchAudioFrame" ],
    [ "MatchBall", "structMatchBall.html", "structMatchBall" ],
    [ "MatchCamera3D", "classMatchCamera3D.html", "classMatchCamera3D" ],
    [ "MatchCameraControl", "structMatchCameraControl.html", "structMatchCameraControl" ],
    [ "MatchCameraFocus", "structMatchCameraFocus.html", "structMatchCameraFocus" ],
    [ "MatchCameraInput", "structMatchCameraInput.html", "structMatchCameraInput" ],
    [ "MatchCommandRecord", "structMatchCommandRecord.html", "structMatchCommandRecord" ],
    [ "MatchCommentaryNames", "structMatchCommentaryNames.html", "structMatchCommentaryNames" ],
    [ "MatchContext", "structMatchContext.html", "structMatchContext" ],
    [ "MatchDetail", "structMatchDetail.html", "structMatchDetail" ],
    [ "MatchEngine", "classMatchEngine.html", "classMatchEngine" ],
    [ "MatchEvent", "structMatchEvent.html", "structMatchEvent" ],
    [ "MatchEventCursor", "classMatchEventCursor.html", "classMatchEventCursor" ],
    [ "MatchHighlight", "structMatchHighlight.html", "structMatchHighlight" ],
    [ "MatchInputRecord", "structMatchInputRecord.html", "structMatchInputRecord" ],
    [ "MatchInsightsView", "classMatchInsightsView.html", "classMatchInsightsView" ],
    [ "MatchKits", "structMatchKits.html", "structMatchKits" ],
    [ "MatchPlayController", "classMatchPlayController.html", "classMatchPlayController" ],
    [ "MatchPlayer", "structMatchPlayer.html", "structMatchPlayer" ],
    [ "MatchPlayerInput", "structMatchPlayerInput.html", "structMatchPlayerInput" ],
    [ "MatchPlayOverlayState", "structMatchPlayOverlayState.html", "structMatchPlayOverlayState" ],
    [ "MatchRender2DTuning", "structMatchRender2DTuning.html", "structMatchRender2DTuning" ],
    [ "MatchRender3DTuning", "structMatchRender3DTuning.html", "structMatchRender3DTuning" ],
    [ "MatchRenderBall", "structMatchRenderBall.html", "structMatchRenderBall" ],
    [ "MatchRenderer2D", "classMatchRenderer2D.html", "classMatchRenderer2D" ],
    [ "MatchRenderer3D", "classMatchRenderer3D.html", "classMatchRenderer3D" ],
    [ "MatchRenderOptions", "structMatchRenderOptions.html", "structMatchRenderOptions" ],
    [ "MatchRenderPlayer", "structMatchRenderPlayer.html", "structMatchRenderPlayer" ],
    [ "MatchRenderSnapshot", "structMatchRenderSnapshot.html", "structMatchRenderSnapshot" ],
    [ "MatchReport", "structMatchReport.html", "structMatchReport" ],
    [ "MatchReportEvent", "structMatchReportEvent.html", "structMatchReportEvent" ],
    [ "MatchReportScene", "classMatchReportScene.html", "classMatchReportScene" ],
    [ "MatchScenario", "structMatchScenario.html", "structMatchScenario" ],
    [ "MatchScenarioPlayer", "structMatchScenarioPlayer.html", "structMatchScenarioPlayer" ],
    [ "MatchScene", "classMatchScene.html", "classMatchScene" ],
    [ "MatchSceneTuning", "structMatchSceneTuning.html", "structMatchSceneTuning" ],
    [ "MatchScheduler", "classMatchScheduler.html", "classMatchScheduler" ],
    [ "MatchShirtNumbers", "classMatchShirtNumbers.html", "classMatchShirtNumbers" ],
    [ "MatchSimulationInput", "structMatchSimulationInput.html", "structMatchSimulationInput" ],
    [ "MatchSimulationResult", "structMatchSimulationResult.html", "structMatchSimulationResult" ],
    [ "MatchStats", "structMatchStats.html", "structMatchStats" ],
    [ "MatchSubsPanel", "classMatchSubsPanel.html", "classMatchSubsPanel" ],
    [ "MatchSubstitution", "structMatchSubstitution.html", "structMatchSubstitution" ],
    [ "MatchTacticsPanel", "classMatchTacticsPanel.html", "classMatchTacticsPanel" ],
    [ "MatchTracker", "classMatchTracker.html", "classMatchTracker" ],
    [ "MatchTuning", "structMatchTuning.html", "structMatchTuning" ],
    [ "Matchup", "structMatchup.html", "structMatchup" ],
    [ "MatchViewport", "structMatchViewport.html", "structMatchViewport" ],
    [ "MedicalDesk", "classMedicalDesk.html", "classMedicalDesk" ],
    [ "MedicalInjuryRow", "structMedicalInjuryRow.html", "structMedicalInjuryRow" ],
    [ "MedicalReport", "structMedicalReport.html", "structMedicalReport" ],
    [ "MedicalRiskRow", "structMedicalRiskRow.html", "structMedicalRiskRow" ],
    [ "MedicalScene", "classMedicalScene.html", "classMedicalScene" ],
    [ "MenteeState", "structMenteeState.html", "structMenteeState" ],
    [ "MentoringDialog", "classMentoringDialog.html", "classMentoringDialog" ],
    [ "MentoringGroup", "structMentoringGroup.html", "structMentoringGroup" ],
    [ "MentoringSystem", "classMentoringSystem.html", "classMentoringSystem" ],
    [ "MetricComparison", "structMetricComparison.html", "structMetricComparison" ],
    [ "NamePool", "structNamePool.html", "structNamePool" ],
    [ "NameRegistry", "classNameRegistry.html", "classNameRegistry" ],
    [ "NationalApplication", "structNationalApplication.html", "structNationalApplication" ],
    [ "NationalDayEvents", "structNationalDayEvents.html", "structNationalDayEvents" ],
    [ "NationalJob", "structNationalJob.html", "structNationalJob" ],
    [ "NationalJobOffer", "structNationalJobOffer.html", "structNationalJobOffer" ],
    [ "NationalManagement", "classNationalManagement.html", "classNationalManagement" ],
    [ "NationalStint", "structNationalStint.html", "structNationalStint" ],
    [ "NationalTeams", "classNationalTeams.html", "classNationalTeams" ],
    [ "NationalVacancy", "structNationalVacancy.html", "structNationalVacancy" ],
    [ "NavEntry", "structNavEntry.html", "structNavEntry" ],
    [ "NavHistory", "classNavHistory.html", "classNavHistory" ],
    [ "Negotiation", "structNegotiation.html", "structNegotiation" ],
    [ "NewsCompetition", "structNewsCompetition.html", "structNewsCompetition" ],
    [ "NewsFilter", "structNewsFilter.html", "structNewsFilter" ],
    [ "NewsItem", "structNewsItem.html", "structNewsItem" ],
    [ "NewsScene", "classNewsScene.html", "classNewsScene" ],
    [ "NewsSources", "structNewsSources.html", "structNewsSources" ],
    [ "NextAction", "structNextAction.html", "structNextAction" ],
    [ "NextActionFacts", "structNextActionFacts.html", "structNextActionFacts" ],
    [ "NextStepsCard", "classNextStepsCard.html", "classNextStepsCard" ],
    [ "OfferNegotiationDialog", "classOfferNegotiationDialog.html", "classOfferNegotiationDialog" ],
    [ "OfferRound", "structOfferRound.html", "structOfferRound" ],
    [ "OnboardingState", "classOnboardingState.html", "classOnboardingState" ],
    [ "OpponentOption", "structOpponentOption.html", "structOpponentOption" ],
    [ "OppositionAverages", "structOppositionAverages.html", "structOppositionAverages" ],
    [ "OppositionInput", "structOppositionInput.html", "structOppositionInput" ],
    [ "OppositionOrder", "structOppositionOrder.html", "structOppositionOrder" ],
    [ "OppositionPlan", "classOppositionPlan.html", "classOppositionPlan" ],
    [ "OppositionPlayer", "structOppositionPlayer.html", "structOppositionPlayer" ],
    [ "OppositionReport", "structOppositionReport.html", "structOppositionReport" ],
    [ "OppositionScene", "classOppositionScene.html", "classOppositionScene" ],
    [ "PassDecision", "structPassDecision.html", "structPassDecision" ],
    [ "PassLink", "structPassLink.html", "structPassLink" ],
    [ "PlannerNeed", "structPlannerNeed.html", "structPlannerNeed" ],
    [ "PlannerPlayer", "structPlannerPlayer.html", "structPlannerPlayer" ],
    [ "Player", "classPlayer.html", "classPlayer" ],
    [ "PlayerAnalyticsRow", "structPlayerAnalyticsRow.html", "structPlayerAnalyticsRow" ],
    [ "PlayerCompareScene", "classPlayerCompareScene.html", "classPlayerCompareScene" ],
    [ "PlayerDynamics", "structPlayerDynamics.html", "structPlayerDynamics" ],
    [ "PlayerInstruction", "structPlayerInstruction.html", "structPlayerInstruction" ],
    [ "PlayerMarketFlags", "structPlayerMarketFlags.html", "structPlayerMarketFlags" ],
    [ "PlayerMatchConsequence", "structPlayerMatchConsequence.html", "structPlayerMatchConsequence" ],
    [ "PlayerMatchLine", "structPlayerMatchLine.html", "structPlayerMatchLine" ],
    [ "PlayerMatchSnapshot", "structPlayerMatchSnapshot.html", "structPlayerMatchSnapshot" ],
    [ "PlayerMatchStats", "structPlayerMatchStats.html", "structPlayerMatchStats" ],
    [ "PlayerNote", "structPlayerNote.html", "structPlayerNote" ],
    [ "PlayerProfileScene", "classPlayerProfileScene.html", "classPlayerProfileScene" ],
    [ "PlayerRelation", "structPlayerRelation.html", "structPlayerRelation" ],
    [ "PlayerRepository", "classPlayerRepository.html", "classPlayerRepository" ],
    [ "PlayerSeasonStats", "structPlayerSeasonStats.html", "structPlayerSeasonStats" ],
    [ "PlayerTalkDialog", "classPlayerTalkDialog.html", "classPlayerTalkDialog" ],
    [ "PlayerTrainingState", "structPlayerTrainingState.html", "structPlayerTrainingState" ],
    [ "PlayerTraits", "structPlayerTraits.html", "structPlayerTraits" ],
    [ "PlayScreenBasis", "structPlayScreenBasis.html", "structPlayScreenBasis" ],
    [ "PreContractDeal", "structPreContractDeal.html", "structPreContractDeal" ],
    [ "PreseasonPlanner", "classPreseasonPlanner.html", "classPreseasonPlanner" ],
    [ "PreseasonScene", "classPreseasonScene.html", "classPreseasonScene" ],
    [ "PreseasonState", "structPreseasonState.html", "structPreseasonState" ],
    [ "ProjectQuote", "structProjectQuote.html", "structProjectQuote" ],
    [ "ProjectRequestContext", "structProjectRequestContext.html", "structProjectRequestContext" ],
    [ "Promise", "structPromise.html", "structPromise" ],
    [ "QueryMapEntry", "structQueryMapEntry.html", "structQueryMapEntry" ],
    [ "RecordBook", "classRecordBook.html", "classRecordBook" ],
    [ "RecordEntry", "structRecordEntry.html", "structRecordEntry" ],
    [ "RecordsScene", "classRecordsScene.html", "classRecordsScene" ],
    [ "RecruitmentFocus", "structRecruitmentFocus.html", "structRecruitmentFocus" ],
    [ "ReserveQuota", "structReserveQuota.html", "structReserveQuota" ],
    [ "ReservesScene", "classReservesScene.html", "classReservesScene" ],
    [ "ReturnWindow", "structReturnWindow.html", "structReturnWindow" ],
    [ "RoleFocus", "structRoleFocus.html", "structRoleFocus" ],
    [ "RoleProfile", "structRoleProfile.html", "structRoleProfile" ],
    [ "RoleUtils", "classRoleUtils.html", "classRoleUtils" ],
    [ "RoleWeights", "structRoleWeights.html", "structRoleWeights" ],
    [ "RosterScene", "classRosterScene.html", "classRosterScene" ],
    [ "RuntimePaths", "classRuntimePaths.html", "classRuntimePaths" ],
    [ "SaveBackup", "structSaveBackup.html", "structSaveBackup" ],
    [ "SaveError", "structSaveError.html", "structSaveError" ],
    [ "SaveFailure", "classSaveFailure.html", "classSaveFailure" ],
    [ "SaveInspection", "structSaveInspection.html", "structSaveInspection" ],
    [ "SaveManager", "classSaveManager.html", "classSaveManager" ],
    [ "SaveMetadata", "structSaveMetadata.html", "structSaveMetadata" ],
    [ "SaveTimings", "structSaveTimings.html", "structSaveTimings" ],
    [ "ScenarioDecision", "structScenarioDecision.html", "structScenarioDecision" ],
    [ "ScopedRenderScale", "classScopedRenderScale.html", "classScopedRenderScale" ],
    [ "ScoutAssignment", "structScoutAssignment.html", "structScoutAssignment" ],
    [ "ScoutedAttribute", "structScoutedAttribute.html", "structScoutedAttribute" ],
    [ "ScoutedPlayerRow", "structScoutedPlayerRow.html", "structScoutedPlayerRow" ],
    [ "ScoutedPlayerView", "structScoutedPlayerView.html", "structScoutedPlayerView" ],
    [ "ScoutEffectiveness", "structScoutEffectiveness.html", "structScoutEffectiveness" ],
    [ "ScoutExpertise", "structScoutExpertise.html", "structScoutExpertise" ],
    [ "ScoutingRepository", "classScoutingRepository.html", "classScoutingRepository" ],
    [ "ScoutingScene", "classScoutingScene.html", "classScoutingScene" ],
    [ "ScoutingState", "structScoutingState.html", "structScoutingState" ],
    [ "ScoutingSystem", "classScoutingSystem.html", "classScoutingSystem" ],
    [ "ScoutKnowledge", "structScoutKnowledge.html", "structScoutKnowledge" ],
    [ "ScoutProfile", "structScoutProfile.html", "structScoutProfile" ],
    [ "ScoutReport", "structScoutReport.html", "structScoutReport" ],
    [ "ScoutSearchFilter", "structScoutSearchFilter.html", "structScoutSearchFilter" ],
    [ "ScoutSummary", "structScoutSummary.html", "structScoutSummary" ],
    [ "SeasonArchive", "classSeasonArchive.html", "classSeasonArchive" ],
    [ "SeasonHistoryEntry", "structSeasonHistoryEntry.html", "structSeasonHistoryEntry" ],
    [ "SeasonReview", "structSeasonReview.html", "structSeasonReview" ],
    [ "SeasonReviewDialog", "classSeasonReviewDialog.html", "classSeasonReviewDialog" ],
    [ "SeasonVerdictInputs", "structSeasonVerdictInputs.html", "structSeasonVerdictInputs" ],
    [ "SeasonVerdictResult", "structSeasonVerdictResult.html", "structSeasonVerdictResult" ],
    [ "SetPiecesDialog", "classSetPiecesDialog.html", "classSetPiecesDialog" ],
    [ "SetPieceSummary", "structSetPieceSummary.html", "structSetPieceSummary" ],
    [ "Settings", "structSettings.html", "structSettings" ],
    [ "SettingsManager", "classSettingsManager.html", "classSettingsManager" ],
    [ "SettingsScene", "classSettingsScene.html", "classSettingsScene" ],
    [ "ShortlistEntry", "structShortlistEntry.html", "structShortlistEntry" ],
    [ "ShotRecord", "structShotRecord.html", "structShotRecord" ],
    [ "SideSummary", "structSideSummary.html", "structSideSummary" ],
    [ "SimulationProgress", "structSimulationProgress.html", "structSimulationProgress" ],
    [ "SlotInstruction", "structSlotInstruction.html", "structSlotInstruction" ],
    [ "SocialGroup", "structSocialGroup.html", "structSocialGroup" ],
    [ "SQLLoader", "classSQLLoader.html", "classSQLLoader" ],
    [ "SquadComparisonRow", "structSquadComparisonRow.html", "structSquadComparisonRow" ],
    [ "SquadPlan", "structSquadPlan.html", "structSquadPlan" ],
    [ "SquadPlannerScene", "classSquadPlannerScene.html", "classSquadPlannerScene" ],
    [ "SquadStatusBook", "classSquadStatusBook.html", "classSquadStatusBook" ],
    [ "SquadSurnames", "classSquadSurnames.html", "classSquadSurnames" ],
    [ "StaffEffects", "structStaffEffects.html", "structStaffEffects" ],
    [ "StaffMember", "structStaffMember.html", "structStaffMember" ],
    [ "StaffRepository", "classStaffRepository.html", "classStaffRepository" ],
    [ "StaffRoster", "classStaffRoster.html", "classStaffRoster" ],
    [ "StaffScene", "classStaffScene.html", "classStaffScene" ],
    [ "StandingRow", "structStandingRow.html", "structStandingRow" ],
    [ "StandingsScene", "classStandingsScene.html", "classStandingsScene" ],
    [ "StatsConfig", "structStatsConfig.html", "structStatsConfig" ],
    [ "StoredLineup", "structStoredLineup.html", "structStoredLineup" ],
    [ "StoredPositionedPlayer", "structStoredPositionedPlayer.html", "structStoredPositionedPlayer" ],
    [ "StoryChoice", "structStoryChoice.html", "structStoryChoice" ],
    [ "StoryDayContext", "structStoryDayContext.html", "structStoryDayContext" ],
    [ "StoryEngine", "classStoryEngine.html", "classStoryEngine" ],
    [ "StoryRecord", "structStoryRecord.html", "structStoryRecord" ],
    [ "StoryState", "structStoryState.html", "structStoryState" ],
    [ "Strategy", "classStrategy.html", "classStrategy" ],
    [ "StrategyScene", "classStrategyScene.html", "classStrategyScene" ],
    [ "StrategySliders", "structStrategySliders.html", "structStrategySliders" ],
    [ "SupporterFacts", "structSupporterFacts.html", "structSupporterFacts" ],
    [ "SupporterMood", "structSupporterMood.html", "structSupporterMood" ],
    [ "SupporterReason", "structSupporterReason.html", "structSupporterReason" ],
    [ "Supporters", "classSupporters.html", "classSupporters" ],
    [ "SwipeGesture", "classSwipeGesture.html", "classSwipeGesture" ],
    [ "SwipeTuning", "structSwipeTuning.html", "structSwipeTuning" ],
    [ "TacticSnapshot", "structTacticSnapshot.html", "structTacticSnapshot" ],
    [ "TalkContext", "structTalkContext.html", "structTalkContext" ],
    [ "TalkListener", "structTalkListener.html", "structTalkListener" ],
    [ "TalkOptionView", "structTalkOptionView.html", "structTalkOptionView" ],
    [ "TalkOutcome", "structTalkOutcome.html", "structTalkOutcome" ],
    [ "TalksCooldown", "structTalksCooldown.html", "structTalksCooldown" ],
    [ "TargetCountry", "structTargetCountry.html", "structTargetCountry" ],
    [ "Team", "classTeam.html", "classTeam" ],
    [ "TeamAnalytics", "structTeamAnalytics.html", "structTeamAnalytics" ],
    [ "TeamMatchStats", "structTeamMatchStats.html", "structTeamMatchStats" ],
    [ "TeamRepository", "classTeamRepository.html", "classTeamRepository" ],
    [ "TeamSelectionScene", "classTeamSelectionScene.html", "classTeamSelectionScene" ],
    [ "TeamTalkContext", "structTeamTalkContext.html", "structTeamTalkContext" ],
    [ "TeamTalkDialog", "classTeamTalkDialog.html", "classTeamTalkDialog" ],
    [ "TeamTalkPrediction", "structTeamTalkPrediction.html", "structTeamTalkPrediction" ],
    [ "TeamTalkResult", "structTeamTalkResult.html", "structTeamTalkResult" ],
    [ "TeamTrainingPlan", "structTeamTrainingPlan.html", "structTeamTrainingPlan" ],
    [ "TeamTrendPoint", "structTeamTrendPoint.html", "structTeamTrendPoint" ],
    [ "ThreadPool", "classThreadPool.html", "classThreadPool" ],
    [ "TimelineEntry", "structTimelineEntry.html", "structTimelineEntry" ],
    [ "TimelineScene", "classTimelineScene.html", "classTimelineScene" ],
    [ "TimelineSources", "structTimelineSources.html", "structTimelineSources" ],
    [ "TouchlineContext", "structTouchlineContext.html", "structTouchlineContext" ],
    [ "TrackedPlayer", "structTrackedPlayer.html", "structTrackedPlayer" ],
    [ "TrackedShot", "structTrackedShot.html", "structTrackedShot" ],
    [ "TrainingAdvice", "structTrainingAdvice.html", "structTrainingAdvice" ],
    [ "TrainingDay", "structTrainingDay.html", "structTrainingDay" ],
    [ "TrainingRegistry", "classTrainingRegistry.html", "classTrainingRegistry" ],
    [ "TrainingRepository", "classTrainingRepository.html", "classTrainingRepository" ],
    [ "TrainingScene", "classTrainingScene.html", "classTrainingScene" ],
    [ "TrainingSlot", "structTrainingSlot.html", "structTrainingSlot" ],
    [ "TransferListing", "structTransferListing.html", "structTransferListing" ],
    [ "TransferMarket", "classTransferMarket.html", "classTransferMarket" ],
    [ "TransferMarketScene", "classTransferMarketScene.html", "classTransferMarketScene" ],
    [ "TransferMarketSceneTuning", "structTransferMarketSceneTuning.html", "structTransferMarketSceneTuning" ],
    [ "TransferObligation", "structTransferObligation.html", "structTransferObligation" ],
    [ "TransferRecord", "structTransferRecord.html", "structTransferRecord" ],
    [ "TransferRepository", "classTransferRepository.html", "classTransferRepository" ],
    [ "TransferTuning", "structTransferTuning.html", "structTransferTuning" ],
    [ "UpcomingFixture", "structUpcomingFixture.html", "structUpcomingFixture" ],
    [ "UpgradeQuote", "structUpgradeQuote.html", "structUpgradeQuote" ],
    [ "Vacancy", "structVacancy.html", "structVacancy" ],
    [ "Vector2F", "structVector2F.html", "structVector2F" ],
    [ "WelcomeTour", "classWelcomeTour.html", "classWelcomeTour" ],
    [ "WorldRng", "classWorldRng.html", "classWorldRng" ],
    [ "WorldSimulation", "classWorldSimulation.html", "classWorldSimulation" ],
    [ "WorldStateRepository", "classWorldStateRepository.html", "classWorldStateRepository" ],
    [ "WorldTuning", "structWorldTuning.html", "structWorldTuning" ],
    [ "YouthAcademy", "classYouthAcademy.html", "classYouthAcademy" ],
    [ "YouthEstimate", "structYouthEstimate.html", "structYouthEstimate" ],
    [ "YouthProgressPoint", "structYouthProgressPoint.html", "structYouthProgressPoint" ],
    [ "YouthRecord", "structYouthRecord.html", "structYouthRecord" ],
    [ "YouthResult", "structYouthResult.html", "structYouthResult" ],
    [ "YouthScene", "classYouthScene.html", "classYouthScene" ],
    [ "YouthTableRow", "structYouthTableRow.html", "structYouthTableRow" ]
];