var hierarchy =
[
    [ "Button", "structButton.html", null ],
    [ "ButtonManager", "classButtonManager.html", null ],
    [ "ButtonStyle", "structButtonStyle.html", null ],
    [ "Calendar", "classCalendar.html", null ],
    [ "DatabaseConnection", "classDatabaseConnection.html", null ],
    [ "DataGenerator", "classDataGenerator.html", null ],
    [ "Dropdown", "classDropdown.html", null ],
    [ "DropdownStyle", "structDropdownStyle.html", null ],
    [ "Finances", "classFinances.html", null ],
    [ "FixtureRepository", "classFixtureRepository.html", null ],
    [ "Game", "classGame.html", null ],
    [ "GameController", "classGameController.html", null ],
    [ "GameData", "classGameData.html", null ],
    [ "GameDate", "classGameDate.html", null ],
    [ "GameDateValue", "structGameDateValue.html", null ],
    [ "GameStateRepository", "classGameStateRepository.html", null ],
    [ "GUIScene", "classGUIScene.html", [
      [ "MainGameScene", "classMainGameScene.html", null ],
      [ "MainMenuScene", "classMainMenuScene.html", null ],
      [ "RosterScene", "classRosterScene.html", null ],
      [ "SettingsScene", "classSettingsScene.html", null ],
      [ "StrategyScene", "classStrategyScene.html", null ],
      [ "TeamSelectionScene", "classTeamSelectionScene.html", null ]
    ] ],
    [ "GUIView", "classGUIView.html", null ],
    [ "LanguageManager", "classLanguageManager.html", null ],
    [ "League", "classLeague.html", null ],
    [ "LeagueRepository", "classLeagueRepository.html", null ],
    [ "Lineup", "classLineup.html", null ],
    [ "Logger", "classLogger.html", null ],
    [ "Match", "classMatch.html", null ],
    [ "Matchup", "structMatchup.html", null ],
    [ "Player", "classPlayer.html", null ],
    [ "PlayerRepository", "classPlayerRepository.html", null ],
    [ "QueryMapEntry", "structQueryMapEntry.html", null ],
    [ "GUIConstants::Resolution", "structGUIConstants_1_1Resolution.html", null ],
    [ "RoleFocus", "structRoleFocus.html", null ],
    [ "RoleWeights", "structRoleWeights.html", null ],
    [ "std::runtime_error", null, [
      [ "DatabaseException", "classDatabaseException.html", null ]
    ] ],
    [ "GameController::SaveSlotMetadata", "structGameController_1_1SaveSlotMetadata.html", null ],
    [ "Settings", "structSettings.html", null ],
    [ "SettingsManager", "classSettingsManager.html", null ],
    [ "SQLLoader", "classSQLLoader.html", null ],
    [ "StatsConfig", "structStatsConfig.html", null ],
    [ "Strategy", "classStrategy.html", null ],
    [ "StrategySliders", "structStrategySliders.html", null ],
    [ "Team", "classTeam.html", null ],
    [ "TeamRepository", "classTeamRepository.html", null ]
];