var match__tuning_8h =
[
    [ "MatchTuning", "structMatchTuning.html", "structMatchTuning" ],
    [ "MatchTuning::Pitch", "structMatchTuning_1_1Pitch.html", "structMatchTuning_1_1Pitch" ],
    [ "MatchTuning::Timing", "structMatchTuning_1_1Timing.html", "structMatchTuning_1_1Timing" ],
    [ "MatchTuning::Playback", "structMatchTuning_1_1Playback.html", "structMatchTuning_1_1Playback" ],
    [ "MatchTuning::Player", "structMatchTuning_1_1Player.html", "structMatchTuning_1_1Player" ],
    [ "MatchTuning::Dribble", "structMatchTuning_1_1Dribble.html", "structMatchTuning_1_1Dribble" ],
    [ "MatchTuning::Load", "structMatchTuning_1_1Load.html", "structMatchTuning_1_1Load" ],
    [ "MatchTuning::Shape", "structMatchTuning_1_1Shape.html", "structMatchTuning_1_1Shape" ],
    [ "MatchTuning::Decision", "structMatchTuning_1_1Decision.html", "structMatchTuning_1_1Decision" ],
    [ "MatchTuning::Passing", "structMatchTuning_1_1Passing.html", "structMatchTuning_1_1Passing" ],
    [ "MatchTuning::Shooting", "structMatchTuning_1_1Shooting.html", "structMatchTuning_1_1Shooting" ],
    [ "MatchTuning::Defending", "structMatchTuning_1_1Defending.html", "structMatchTuning_1_1Defending" ],
    [ "MatchTuning::Ball", "structMatchTuning_1_1Ball.html", "structMatchTuning_1_1Ball" ],
    [ "MatchTuning::Rules", "structMatchTuning_1_1Rules.html", "structMatchTuning_1_1Rules" ],
    [ "MatchTuning::Goalkeeper", "structMatchTuning_1_1Goalkeeper.html", "structMatchTuning_1_1Goalkeeper" ],
    [ "MatchTuning::SetPiece", "structMatchTuning_1_1SetPiece.html", "structMatchTuning_1_1SetPiece" ],
    [ "MatchTuning::Units", "structMatchTuning_1_1Units.html", "structMatchTuning_1_1Units" ],
    [ "MatchTuning::Rating", "structMatchTuning_1_1Rating.html", "structMatchTuning_1_1Rating" ],
    [ "MatchTuning::Discipline", "structMatchTuning_1_1Discipline.html", "structMatchTuning_1_1Discipline" ],
    [ "MatchTuning::Injury", "structMatchTuning_1_1Injury.html", "structMatchTuning_1_1Injury" ],
    [ "MatchTuning::Stoppage", "structMatchTuning_1_1Stoppage.html", "structMatchTuning_1_1Stoppage" ],
    [ "MatchTuning::Substitution", "structMatchTuning_1_1Substitution.html", "structMatchTuning_1_1Substitution" ],
    [ "MatchTuning::Fatigue", "structMatchTuning_1_1Fatigue.html", "structMatchTuning_1_1Fatigue" ],
    [ "MatchTuning::Aerial", "structMatchTuning_1_1Aerial.html", "structMatchTuning_1_1Aerial" ],
    [ "MatchTuning::Touchline", "structMatchTuning_1_1Touchline.html", "structMatchTuning_1_1Touchline" ],
    [ "MatchTuning::Control", "structMatchTuning_1_1Control.html", "structMatchTuning_1_1Control" ],
    [ "MatchTuning::Context", "structMatchTuning_1_1Context.html", "structMatchTuning_1_1Context" ],
    [ "MatchTuning::Statistics", "structMatchTuning_1_1Statistics.html", "structMatchTuning_1_1Statistics" ]
];