var structMatchRender3DTuning =
[
    [ "Ball", "structMatchRender3DTuning_1_1Ball.html", "structMatchRender3DTuning_1_1Ball" ],
    [ "Boards", "structMatchRender3DTuning_1_1Boards.html", "structMatchRender3DTuning_1_1Boards" ],
    [ "Broadcast", "structMatchRender3DTuning_1_1Broadcast.html", "structMatchRender3DTuning_1_1Broadcast" ],
    [ "Camera", "structMatchRender3DTuning_1_1Camera.html", "structMatchRender3DTuning_1_1Camera" ],
    [ "Celebration", "structMatchRender3DTuning_1_1Celebration.html", "structMatchRender3DTuning_1_1Celebration" ],
    [ "CornerFlag", "structMatchRender3DTuning_1_1CornerFlag.html", "structMatchRender3DTuning_1_1CornerFlag" ],
    [ "Crowd", "structMatchRender3DTuning_1_1Crowd.html", "structMatchRender3DTuning_1_1Crowd" ],
    [ "Day", "structMatchRender3DTuning_1_1Day.html", "structMatchRender3DTuning_1_1Day" ],
    [ "Director", "structMatchRender3DTuning_1_1Director.html", "structMatchRender3DTuning_1_1Director" ],
    [ "End", "structMatchRender3DTuning_1_1End.html", "structMatchRender3DTuning_1_1End" ],
    [ "Floodlight", "structMatchRender3DTuning_1_1Floodlight.html", "structMatchRender3DTuning_1_1Floodlight" ],
    [ "Follow", "structMatchRender3DTuning_1_1Follow.html", "structMatchRender3DTuning_1_1Follow" ],
    [ "Free", "structMatchRender3DTuning_1_1Free.html", "structMatchRender3DTuning_1_1Free" ],
    [ "Gait", "structMatchRender3DTuning_1_1Gait.html", "structMatchRender3DTuning_1_1Gait" ],
    [ "Goal", "structMatchRender3DTuning_1_1Goal.html", "structMatchRender3DTuning_1_1Goal" ],
    [ "Grass", "structMatchRender3DTuning_1_1Grass.html", "structMatchRender3DTuning_1_1Grass" ],
    [ "Hud", "structMatchRender3DTuning_1_1Hud.html", "structMatchRender3DTuning_1_1Hud" ],
    [ "Keeper", "structMatchRender3DTuning_1_1Keeper.html", "structMatchRender3DTuning_1_1Keeper" ],
    [ "Kick", "structMatchRender3DTuning_1_1Kick.html", "structMatchRender3DTuning_1_1Kick" ],
    [ "Light", "structMatchRender3DTuning_1_1Light.html", "structMatchRender3DTuning_1_1Light" ],
    [ "Markings", "structMatchRender3DTuning_1_1Markings.html", "structMatchRender3DTuning_1_1Markings" ],
    [ "Number", "structMatchRender3DTuning_1_1Number.html", "structMatchRender3DTuning_1_1Number" ],
    [ "Play", "structMatchRender3DTuning_1_1Play.html", "structMatchRender3DTuning_1_1Play" ],
    [ "Player", "structMatchRender3DTuning_1_1Player.html", "structMatchRender3DTuning_1_1Player" ],
    [ "Pose", "structMatchRender3DTuning_1_1Pose.html", "structMatchRender3DTuning_1_1Pose" ],
    [ "Rig", "structMatchRender3DTuning_1_1Rig.html", "structMatchRender3DTuning_1_1Rig" ],
    [ "Ripple", "structMatchRender3DTuning_1_1Ripple.html", "structMatchRender3DTuning_1_1Ripple" ],
    [ "Shadow", "structMatchRender3DTuning_1_1Shadow.html", "structMatchRender3DTuning_1_1Shadow" ],
    [ "Sky", "structMatchRender3DTuning_1_1Sky.html", "structMatchRender3DTuning_1_1Sky" ],
    [ "Stands", "structMatchRender3DTuning_1_1Stands.html", "structMatchRender3DTuning_1_1Stands" ],
    [ "Sting", "structMatchRender3DTuning_1_1Sting.html", "structMatchRender3DTuning_1_1Sting" ],
    [ "Tactical", "structMatchRender3DTuning_1_1Tactical.html", "structMatchRender3DTuning_1_1Tactical" ]
];