var structMatchTuning =
[
    [ "Aerial", "structMatchTuning_1_1Aerial.html", "structMatchTuning_1_1Aerial" ],
    [ "Ball", "structMatchTuning_1_1Ball.html", "structMatchTuning_1_1Ball" ],
    [ "Context", "structMatchTuning_1_1Context.html", "structMatchTuning_1_1Context" ],
    [ "Control", "structMatchTuning_1_1Control.html", "structMatchTuning_1_1Control" ],
    [ "Decision", "structMatchTuning_1_1Decision.html", "structMatchTuning_1_1Decision" ],
    [ "Defending", "structMatchTuning_1_1Defending.html", "structMatchTuning_1_1Defending" ],
    [ "Discipline", "structMatchTuning_1_1Discipline.html", "structMatchTuning_1_1Discipline" ],
    [ "Dribble", "structMatchTuning_1_1Dribble.html", "structMatchTuning_1_1Dribble" ],
    [ "Fatigue", "structMatchTuning_1_1Fatigue.html", "structMatchTuning_1_1Fatigue" ],
    [ "Goalkeeper", "structMatchTuning_1_1Goalkeeper.html", "structMatchTuning_1_1Goalkeeper" ],
    [ "Injury", "structMatchTuning_1_1Injury.html", "structMatchTuning_1_1Injury" ],
    [ "Load", "structMatchTuning_1_1Load.html", "structMatchTuning_1_1Load" ],
    [ "Passing", "structMatchTuning_1_1Passing.html", "structMatchTuning_1_1Passing" ],
    [ "Pitch", "structMatchTuning_1_1Pitch.html", "structMatchTuning_1_1Pitch" ],
    [ "Playback", "structMatchTuning_1_1Playback.html", "structMatchTuning_1_1Playback" ],
    [ "Player", "structMatchTuning_1_1Player.html", "structMatchTuning_1_1Player" ],
    [ "Rating", "structMatchTuning_1_1Rating.html", "structMatchTuning_1_1Rating" ],
    [ "Rules", "structMatchTuning_1_1Rules.html", "structMatchTuning_1_1Rules" ],
    [ "SetPiece", "structMatchTuning_1_1SetPiece.html", "structMatchTuning_1_1SetPiece" ],
    [ "Shape", "structMatchTuning_1_1Shape.html", "structMatchTuning_1_1Shape" ],
    [ "Shooting", "structMatchTuning_1_1Shooting.html", "structMatchTuning_1_1Shooting" ],
    [ "Statistics", "structMatchTuning_1_1Statistics.html", "structMatchTuning_1_1Statistics" ],
    [ "Stoppage", "structMatchTuning_1_1Stoppage.html", "structMatchTuning_1_1Stoppage" ],
    [ "Substitution", "structMatchTuning_1_1Substitution.html", "structMatchTuning_1_1Substitution" ],
    [ "Timing", "structMatchTuning_1_1Timing.html", "structMatchTuning_1_1Timing" ],
    [ "Touchline", "structMatchTuning_1_1Touchline.html", "structMatchTuning_1_1Touchline" ],
    [ "Units", "structMatchTuning_1_1Units.html", "structMatchTuning_1_1Units" ],
    [ "MatchTuning", "structMatchTuning.html#aaad88df01082e8a885592e7452f3dec0", null ],
    [ "MatchTuning", "structMatchTuning.html#a23add549dbf7991e71965f1f6161224e", null ],
    [ "operator=", "structMatchTuning.html#a55884efbee4e45c9ea4a5132f683950d", null ],
    [ "operator=", "structMatchTuning.html#a5576049e6d1375360815221992841aa5", null ]
];