name: C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup SDL3
      uses: libsdl-org/setup-sdl@main
      with:
        version: 3-latest
        install-linux-dependencies: true

    - name: Install Tools & TTF Dependencies
      run: |
        sudo apt update
        sudo apt install -y \
          clang \
          clang-tidy \
          clang-format \
          cppcheck \
          libsqlite3-dev \
          libfreetype-dev \
          libharfbuzz-dev

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug

    - name: Format check
      run: |
        clang-format --dry-run --Werror $(git ls-files '*.cpp' '*.h')

    - name: Build
      run: cmake --build build -j

    - name: Run tests
      run: ctest --test-dir build --output-on-failure
